### ISSUE TITLE
Support for FocusLost events

### ISSUE THREAD

**Issue by SirVer** [rogual/neovim.app#7]
Vim gui defines some autocommands like `FocusLost` that would be awesome if they were supported.

**Comment by rogual** [comment]
FocusLost is gone from NeoVim it seems — I'm looking to see if this can be done with the api as it stands or if it will need a patch to NeoVim.

**Comment by rogual** [comment]
Ah, nope, wasn't removed, just the code that triggers it. Implementing now.

**Comment by rogual** [comment]
Done and done. https://github.com/rogual/neovim.app/commit/99cedcb26bb0adcdb1f8c2133372233b4faca3fe

**Comment by SirVer** [comment]
that was some quick turnaround time :). Thanks.
