### ISSUE TITLE
Neovim homebrew formula

### ISSUE THREAD

**Issue by fwalch** [rogual/neovim.app#8]
I don't use OS X, so please just close this if I misunderstood how things work.

Neovim has a [homebrew formula](https://github.com/neovim/homebrew-neovim), so maybe you can simplify the setup instructions. You could probably also add a formula to this repo in a similar fashion (don't know if that makes sense with `.app`s).

And a heads up: when neovim/neovim#1927 is merged, your build script will break (replaces use of `$VIM`/`$VIMRUNTIME` with `$NVIM`/`$NVIMRUNTIME`).

**Comment by rogual** [comment]
Thanks for the info re `$VIM` / `$NVIM`. It shouldn't affect the build script (which uses variables with those names for different things) but it will affect the app itself. Commit https://github.com/rogual/neovim.app/commit/aacfa4db7f7931dd9f958b6bec78be7c7367d028 should future-proof it.

Keeping this open until I've had a look at the homebrew stuff.

**Comment by rogual** [comment]
I've updated the readme to point people to Homebrew: https://github.com/rogual/neovim.app/commit/5a3519e2ee1a7ecd3502acc2ce3018c412c237d1

Much clearer, thanks!
